#!/bin/bash
# Legacy MCP Cleanup Script
# Generated by Backend Dev for CLI Reflection Migration

echo "🧹 Starting Legacy MCP Cleanup..."

# 1. FILES TO REMOVE
echo "📁 Removing manual tool directories..."

# Remove tools directory
rm -rf tmux_orchestrator/mcp/tools/
echo "  ✅ Removed tmux_orchestrator/mcp/tools/"

# Remove handlers directory
rm -rf tmux_orchestrator/mcp/handlers/
echo "  ✅ Removed tmux_orchestrator/mcp/handlers/"

# 2. IMPORT REFERENCES TO UPDATE
echo "📝 Cleaning import references..."

# Update server.py - remove manual tool imports
sed -i '/from tmux_orchestrator.mcp.tools.agent_management import/d' tmux_orchestrator/mcp/server.py
echo "  ✅ Cleaned tmux_orchestrator/mcp/server.py"

# Remove test files that test manual tools
rm -f tests/mcp/test_team_operations.py
rm -f tests/mcp/test_fastmcp_phase1.py
rm -f tests/mcp/test_communication.py
rm -f tests/mcp/test_agent_management_tools.py
echo "  ✅ Removed obsolete test files"

# 3. ARCHIVE OBSOLETE DOCS
echo "📚 Archiving obsolete documentation..."
mkdir -p .archive/mcp_manual_tools/
mv -f docs/architecture/mcp-design.md .archive/mcp_manual_tools/ 2>/dev/null || true
echo "  ✅ Archived obsolete MCP documentation"

echo "✨ Legacy MCP cleanup complete!"

# CLEANUP SUMMARY
echo ""
echo "CLEANUP SUMMARY:"
echo "================"
echo "Directories removed: 2"
echo "  - tmux_orchestrator/mcp/tools/"
echo "  - tmux_orchestrator/mcp/handlers/"
echo ""
echo "Files removed: 13+"
echo "  - 4 tool modules"
echo "  - 5 handler modules"
echo "  - 4 test files"
echo ""
echo "Imports cleaned: 1"
echo "  - server.py manual tool import"
echo ""
echo "Documentation archived: 1"
echo "  - mcp-design.md"
