#!/bin/bash
# Quick commands to attach to all agents - copy and paste these into separate terminals

echo "=== QUICK ATTACH COMMANDS ==="
echo ""
echo "Open 4 terminals in VS Code (Terminal > New Terminal or Ctrl+Shift+\`)"
echo "Then run one of these commands in each terminal:"
echo ""
echo "Terminal 1:"
echo "tmux attach-session -t tmux-orc-dev:5  # Project Manager"
echo ""
echo "Terminal 2:"
echo "tmux attach-session -t tmux-orc-dev:2  # MCP Developer"
echo ""
echo "Terminal 3:"
echo "tmux attach-session -t tmux-orc-dev:3  # CLI Developer"
echo ""
echo "Terminal 4:"
echo "tmux attach-session -t tmux-orc-dev:4  # Agent Recovery Developer"
echo ""
echo "TIP: Use VS Code's split terminal feature (click split icon or Ctrl+Shift+5)"
echo "to create a 2x2 grid of terminals for better organization!"